code: cp_admin_config
parentCode: customer_portal
titles:
  en: CP Admin Config
  it: CP Admin Config
pageModel: cp-internal-page
ownerGroup: free
joinGroups: [ ]
displayedInMenu: true
seo: false
charset: utf-8
status: published
widgets:
  - code: language
    config: null
    pos: 0
  - code: cp-login-widget
    config: null
    pos: 2
  - code: logo
    config: null
    pos: 3
  - code: navigation-menu
    config: null
    pos: 5
  - code: cp-admin-configuration-widget
    config: null
    pos: 7
